apiVersion: v1
kind: Pod
metadata:
  name: giropops
  creationTimestamp: "2026-03-05T12:00:00Z"
  labels:
    run: giropops
spec:
  containers:
    - image: nginx
      name: giropops
      ports:
        - containerPort: 80
      resources:
        {
          limits: { cpu: "500m", memory: "128Mi" },
          requests: { cpu: "250m", memory: "64Mi" },
        }
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
